### ISSUE TITLE
micro-ed25519-hdkey - Malicious Package

### ISSUE THREAD

**Issue by x777** [raznorabochiy/wallets-tools#1]
Привет! 

При проверке кода, сканер уязвимостей snyk.io ругается на библиотеку `"micro-ed25519-hdkey": "^0.1.2" ` - [Тут подробнее](https://security.snyk.io/vuln/SNYK-JS-MICROED25519HDKEY-3042063)

![image](https://github.com/raznorabochiy/wallets-tools/assets/4421831/27ac18bd-c34c-42eb-88ff-a7b808085015)

Не факт, конечно, что там есть на самом деле вредоносный код, но библиотека все таки древняя, думаю стоит подумать как обойтись без нее, от греха подальше.

С уважением, [CodeSpec](https://t.me/codespec)!

**Comment by raznorabochiy** [comment]
Привет! Я эту либу использую для кошельков Соланы, её рекомендует разработчики в своей документации - https://solana.com/ar/developers/cookbook/wallets/restore-from-mnemonic 

Попробую найти замену, более трастовую либу

**Comment by raznorabochiy** [comment]
Заменил библиотеку micro-ed25519-hdkey на более популярную ed25519-keygen

https://github.com/raznorabochiy/wallets-tools/commit/86c8f17f728df92044862008f33bd93ef805d41d
